### ISSUE TITLE
ArgumentOutOfRangeException  when adding StatusBarItem

### ISSUE THREAD

**Issue by petsuter** [fluentribbon/Fluent.Ribbon#329]
When `MyWindow` contains a `<Fluent:StatusBar x:Name="statusBar" />` and we do the following:
```
            var w = new MyWindow();
            w.statusBar.Items.Add(new StatusBarItem());
            w.statusBar.Items.Add(new StatusBarItem());
            w.Show();
            w.statusBar.Items.Add(new StatusBarItem());
```
(But not with most different variations, e.g. "3xAdd+Show" or "Show+3xAdd" or "Add+Show+2xAdd" all work fine.)

We get an exception:
```
System.ArgumentOutOfRangeException was unhandled
  HResult=-2146233086
  Message=Insertion index was out of range. Must be non-negative and less than or equal to size.
Parameter name: index
  Source=mscorlib
  ParamName=index
  StackTrace:
       at System.Collections.ArrayList.Insert(Int32 index, Object value)
       at MS.Internal.Controls.InnerItemCollectionView.Insert(Int32 index, Object item)
       at System.Windows.Controls.ItemCollection.Insert(Int32 insertIndex, Object insertItem)
       at Fluent.StatusBar.OnItemsChanged(NotifyCollectionChangedEventArgs e) in C:\projects\fluent-ribbon\Fluent.Ribbon\Controls\StatusBar.cs:line 203
       at System.Windows.Controls.ItemsControl.OnItemCollectionChanged2(Object sender, NotifyCollectionChangedEventArgs e)
       at System.Collections.Specialized.NotifyCollectionChangedEventHandler.Invoke(Object sender, NotifyCollectionChangedEventArgs e)
       at System.Windows.Data.CollectionView.OnCollectionChanged(NotifyCollectionChangedEventArgs args)
       at System.Windows.Controls.ItemCollection.OnViewCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
       at System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
       at System.Windows.WeakEventManager.DeliverEvent(Object sender, EventArgs args)
       at System.Collections.Specialized.CollectionChangedEventManager.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
       at System.Windows.Data.CollectionView.OnCollectionChanged(NotifyCollectionChangedEventArgs args)
       at MS.Internal.Controls.InnerItemCollectionView.Add(Object item)
       at System.Windows.Controls.ItemCollection.Add(Object newItem)
       at FluentStatusBarTest.App.OnStartup(StartupEventArgs e) in c:\FluentStatusBarTest\FluentStatusBarTest\App.xaml.cs:line 27
```

--
### Environment

- Fluent.Ribbon v4.0.3.394
- Windows 10
- .NET Framework 4.5.2

**Comment by batzen** [comment]
Could you attach your repro?

**Comment by petsuter** [comment]
[FluentStatusBarTest_Issue329.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/320626/FluentStatusBarTest_Issue329.zip)
