### ISSUE TITLE
Regarding the outdated FixWindowChromeBugForMaximizedWindow() method

### ISSUE THREAD

**Issue by znakeeye** [fluentribbon/Fluent.Ribbon#634]
Please recall the `FixWindowChromeBugForMaximizedWindow()` method found in **v3.6.0.221**. I'm currently investigating an extremely rare crash where the stack trace merely points to an `UpdateWindowPos` call. The error message tells me that there could perhaps exist an infinite loop of calls to `PostMessage` or something like that. Yeah, it's hard to analyze... But!

Looking at the source code for v3.6.0.221 I found this `FixWindowChromeBugForMaximizedWindow()` method which is being called when the window is being maximized. It calls `MoveWindow` twice which, I guess, could then re-trigger the `WM_SIZE` message hook?

**Is it even remotely possible that this old hack could cause this type of error?**

```
Unhandled Exception:Not enough quota is available to process this command

Stack Trace:

   at MS.Win32.UnsafeNativeMethods.PostMessage(HandleRef hwnd, WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by batzen** [comment]
Which version of Fluent.Ribbon are you using?

**Comment by znakeeye** [comment]
v3.6.0.221

**Comment by batzen** [comment]
The current version is 6.1 and 7.0 will most likely be released in november.
So i won't fix issues in any version different than 6.1 and 7.0.
Most of the time i only support the latest version.

**Comment by znakeeye** [comment]
No need for a fix. I'm just asking if you remember any issues/concerns related to this particular method. You are probably the only one alive who knows anything about it :stuck_out_tongue: 

My own conclusion is that this oooold method is indeed dangerous. You can close this issue, but it would be very helpful if you had anything to say about this oooold method.

**Comment by batzen** [comment]
As far as i remember there was no protection against reentrancy in that version so this issue could easily occur under certain conditions.

What's holding you back to update to the latest version of Fluent.Ribbon?

**Comment by znakeeye** [comment]
Thanks for confirming my findings.

Will try to upgrade to v6+ as soon as possible. The reason why we haven't done so is... well, long story short; [red tape](https://en.wikipedia.org/wiki/Red_tape) :stuck_out_tongue:
