### ISSUE TITLE
Exception with 7.0.0-alpha0586 on .NET Core 3 preview 2

### ISSUE THREAD

**Issue by jherby2k** [fluentribbon/Fluent.Ribbon#702]
I'm trying to add a basic ribbon to a new WPF app using .net core 3. When I click on an unrelated control, or hit the Alt key, I get the following exception. No, I don't have any audio controls on this app at all.

Not sure if this happened under any previous alpha.

```
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'System.Media.SoundPlayer, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
  Source=Fluent
  StackTrace:
   at Fluent.KeyTipService.OnWindowPreviewKeyDown(Object sender, KeyEventArgs e)
   at System.Windows.Input.KeyEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at System.Windows.Interop.HwndSource.OnPreprocessMessageThunk(MSG& msg, Boolean& handled)
   at System.Windows.Interop.ComponentDispatcherThread.RaiseThreadMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.TranslateAndDispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at AudioWorks.UI.App.Main()
```

---
### Environment

- Fluent.Ribbon 7.0.0-alpha0586
- Windows 10 1809
- .NET Core 3.0 Preview 2

**Comment by batzen** [comment]
I don't get that exception when using preview 4 of .net core.
Could you update to the latest preview of .net core and try that again?

**Comment by jherby2k** [comment]
Are you from the future? The latest I see is preview 2.

The exception throws when I try to edit a cell in my data grid (but only if fluent ribbon is present on that window)

**Comment by batzen** [comment]
The latest preview is 3.0.100-preview4-010569.
You can download the latest preview from https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-win-x64.exe

**Comment by jherby2k** [comment]
Tested just now - still happens. My minimum repro looks sorta like this. As soon as you try to type a letter in a datagrid cell, the exception is thrown.

```xaml
<fluent:RibbonWindow x:Class="AudioWorks.UI.Views.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:i="http://schemas.microsoft.com/expression/2010/interactivity" 
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:prism="http://prismlibrary.com/"
        xmlns:fluent="urn:fluent-ribbon"
        mc:Ignorable="d"
        prism:ViewModelLocator.AutoWireViewModel="True"
        Title="Test" Height="600" Width="1000">
    <Grid>

        <Grid.RowDefinitions>
            <RowDefinition Height="Auto"/>
            <RowDefinition Height="*"/>
        </Grid.RowDefinitions>

        <fluent:Ribbon>
            <fluent:Ribbon.Menu>
                <fluent:ApplicationMenu>
                    <fluent:MenuItem Header="Open" Command="{Binding OpenFilesCommand}"/>
                    <fluent:MenuItem Header="Exit" Command="{Binding ExitCommand}"/>
                </fluent:ApplicationMenu>
            </fluent:Ribbon.Menu>
        </fluent:Ribbon>

        <DataGrid Grid.Row="1" ItemsSource="{Binding Files}">
            <DataGrid.Columns>
                <DataGridTextColumn Header="Title"/>
            </DataGrid.Columns>
        </DataGrid>

    </Grid>
</fluent:RibbonWindow>

```

**Comment by batzen** [comment]
What stacktrace do you get for the datagrid exception?
Does the datagrid exception also happen when you remove the ribbon?
Have you rebuilt your project with the latest .net core sdk preview?
The exception you originally reported happens because the KeyTipService calls `System.Media.SystemSounds.Beep.Play()`.

**Comment by jherby2k** [comment]
Yeah, its the keyttipservice - it really has nothing to do with the datagrid. You can remove it and just hit Alt to generate the same exception:

```xaml
<fluent:RibbonWindow x:Class="AudioWorks.UI.Views.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:i="http://schemas.microsoft.com/expression/2010/interactivity" 
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:prism="http://prismlibrary.com/"
        xmlns:fluent="urn:fluent-ribbon"
        mc:Ignorable="d"
        prism:ViewModelLocator.AutoWireViewModel="True"
        Title="Test" Height="600" Width="1000">
    <Grid>

        <Grid.RowDefinitions>
            <RowDefinition Height="Auto"/>
        </Grid.RowDefinitions>

        <fluent:Ribbon>
        </fluent:Ribbon>

    </Grid>
</fluent:RibbonWindow>
```

**Comment by batzen** [comment]
I guess something with your .net core installation is wrong.
The problem here is that i can't do anything about this because there seems to be a missing assembly in your .net core installation.
Could you check if `C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\3.0.0-preview4-27501-5\System.Windows.Extensions.dll` exists on your machine?

**Comment by jherby2k** [comment]
Yup its there. file version 4.7.19.12808.

This is with Visual Studio 2019, preview 4. If that matters. You can't repro?

**Comment by batzen** [comment]
No i can't reproduce the issue.
That's why i said something with your .net core preview installation seems to be wrong.

**Comment by jherby2k** [comment]
I've reproduced it on two different machines now. Let me try it with a new project.

**Comment by jherby2k** [comment]
Yep, shockingly easy to reproduce on multiple machines.

1) Create a new .net core WPF project from within Visual Studio 2019 RC or preview 3+
2) Add a fluent:Ribbon control to the main window.
3) Start a debug session and hit the Alt key to bring up keytips.
3) Boom!

If you can't reproduce this, I'd assume its due to the specific build of preview4 you're using. Mine is from yesterday... 3.0.100.10569. I'd like to try yours, but I don't know wheree to find historical builds.

```xaml
<Window x:Class="FluentRepro.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:fluent="urn:fluent-ribbon"
        xmlns:local="clr-namespace:FluentRepro"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="9*"/>
            <RowDefinition Height="1*"/>
        </Grid.RowDefinitions>
        <fluent:Ribbon/>
        <Button Content="Exit" Grid.Row="1" FontSize="20" Click="ButtonExit_Click"/>
    </Grid>
</Window>
```

**Comment by batzen** [comment]
Could you add your repro project to this issue?

**Comment by jherby2k** [comment]
[FluentRepro.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/2926687/FluentRepro.zip)

Again, just run and hit Alt.

**Comment by batzen** [comment]
Just released a new preview of Fluent.Ribbon to nuget which is version 7.0.0-alpha0623.
The problem was that the previous preview referenced an older version of the .net core 3.0 runtime.
That's what you get when you try to support previews ;-)

**Comment by jherby2k** [comment]
Fixed! Thank you sir. And that is what I get for trying to use one :)
