### ISSUE TITLE
RibbonWindow crashes when window is defined in resource library

### ISSUE THREAD

**Issue by pschimmel** [fluentribbon/Fluent.Ribbon#764]
There is a NullReferenceException in 7.0.1 when the ribbon window is not located in the main assembly, but in a resource library dll.

Relevant part of the stack trace:
   at Fluent.RibbonProperties.GetLastVisibleWidth(DependencyObject element)
   at Fluent.RibbonWindow.OnSizeChanged(Object sender, SizeChangedEventArgs e)
   at System.Windows.SizeChangedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)

First I thought it is because the iconImage is not there, but indeed this.WindowCommands.ItemsControl is null. Then RibbonProperties.GetLastVisibleWidth throws an exception because element is null. 
 
I will attach a sample project for testing.

---
### Environment

- Fluent.Ribbon __v7.0.1__
- Windows __10__
- .NET Framework __4.7.2__

**Comment by pschimmel** [comment]
[FluentTest.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/3962326/FluentTest.zip)

**Comment by pschimmel** [comment]
Never mind. I found it.

Of course, I forgot to attach the default theme in App.xaml as written in the documentation.

Next time I'll read the manual first!
