### ISSUE TITLE
ControlTemplate TargetType does not match templated type

### ISSUE THREAD

**Issue by YetAnotherCodeMaker** [fluentribbon/Fluent.Ribbon#831]
In the XAML Designer, I frequently encounter this error. When I open my project and open my window class in the designer, the ribbon is correctly displayed, but after very few manipulations (either in code, or in the designer, I couldn't determine which ones, it seems highly random), this error occurs, sometimes with the Ribbon, sometimes with the BackstageTabControl... (reverting to the version 7.0.0 discards this issue).

---
### Environment

- Fluent.Ribbon 8.0.0
- Windows 10.0.19041
- Visual Studio 16.6.5
- .NET Framework 4.8

Here are the exception details:

**ArgumentException: 'Ribbon' ControlTemplate TargetType does not match templated type 'Ribbon'.**

   at System.Windows.Controls.ControlTemplate.ValidateTemplatedParent(FrameworkElement templatedParent)
   at System.Windows.FrameworkTemplate.ApplyTemplateContent(UncommonField`1 templateDataField, FrameworkElement container)
   at System.Windows.FrameworkElement.ApplyTemplate()
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.InvokeOnRenderCallback.DoWork()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**InnerException: None**

**Comment by batzen** [comment]
Please report WPF designer issues at Visual Studio / Microsoft as there is, most of the time, nothing I can fix in the ribbon to get rid of these issues.

**Comment by YetAnotherCodeMaker** [comment]
I know it’s a problem which happens from time to time, but it never happened with any previous version of Fluent Ribbon I ever used…

**Comment by batzen** [comment]
It happens to me for years, that's why i stopped using the designer completely.
If you have a look at the ribbon style there is only one template and it's target type is correct.

**Comment by YetAnotherCodeMaker** [comment]
I have no doubt the XAML designer is involved (from what I’ve seen debugging it in this case, it complains not targeting a type which is exactly the type It is shown). Usually, a lot of designer errors occur with an error which arises uncatched earlier, but even if I agree the XAML designer is quite weird, I still get nice results with it. Anyway, in this specific case, killing it’s process and reloading it allows to restore the UI (for a variable length of time).
